### ISSUE TITLE
pino-logflare not yet publish on npm

### ISSUE THREAD

**Issue by FuYaoDe** [Logflare/pino-logflare#1]
Hi threre,
This is my debug.log, I think pino-logflare not yet publish on npm.
Npm website search not found too
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/****/.nvm/versions/node/v10.14.2/bin/node',
1 verbose cli   '/Users/****/.nvm/versions/node/v10.14.2/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'pino-logflare' ]
2 info using npm@6.4.1
3 info using node@v10.14.2
4 verbose npm-session 75ebb324218b63bc
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 https://registry.npmjs.org/pino-logflare 921ms
8 silly fetchPackageMetaData error for pino-logflare@latest 404 Not Found: pino-logflare@latest
9 timing stage:rollbackFailedOptional Completed in 2ms
10 timing stage:runTopLevelLifecycles Completed in 1266ms
11 verbose stack Error: 404 Not Found: pino-logflare@latest
11 verbose stack     at fetch.then.res (/Users/****/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
11 verbose stack     at tryCatcher (/Users/****/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (/Users/****/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
11 verbose stack     at Promise._settlePromise (/Users/****/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (/Users/****/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
11 verbose stack     at Promise._settlePromises (/Users/****/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
11 verbose stack     at Async._drainQueue (/Users/****/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
11 verbose stack     at Async._drainQueues (/Users/****/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/Users/****/.nvm/versions/node/v10.14.2/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
11 verbose stack     at runCallback (timers.js:705:18)
11 verbose stack     at tryOnImmediate (timers.js:676:5)
11 verbose stack     at processImmediate (timers.js:658:5)
12 verbose cwd /Users/****/Projects/bamboodd/herehear-api
13 verbose Darwin 18.7.0
14 verbose argv "/Users/****/.nvm/versions/node/v10.14.2/bin/node" "/Users/****/.nvm/versions/node/v10.14.2/bin/npm" "install" "-g" "pino-logflare"
15 verbose node v10.14.2
16 verbose npm  v6.4.1
17 error code E404
18 error 404 Not Found: pino-logflare@latest
19 verbose exit [ 1, true ]

```

Thanks.

**Comment by chasers** [comment]
Doh, done!

https://www.npmjs.com/package/pino-logflare
